name: Patch Lindroid DRM Loopback openai

on:
  workflow_dispatch:

jobs:
  patch-evdi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Repo
      uses: actions/checkout@v4
      with:
        repository: RONNIE158/android_kernel_xiaomi_sdm845
        token: ${{ secrets.GH_TOKEN }}
        ref: lineage-21
        fetch-depth: 0

    - name: Create new branch
      run: git checkout -b lindroid-drm-loopback

    - name: Download and extract EVDI DRM Loopback
      run: |
        wget https://chat.openai.com/mnt/data/lindroid-drm-loopback-master.zip -O evdi.zip
        unzip evdi.zip
        mkdir -p kernel/drivers/gpu/drm/evdi
        cp -r lindroid-drm-loopback-master/* kernel/drivers/gpu/drm/evdi/

    - name: Update DRM Kconfig
      run: |
        echo 'source "drivers/gpu/drm/evdi/Kconfig"' >> drivers/gpu/drm/Kconfig

    - name: Update DRM Makefile
      run: |
        echo 'obj-$(CONFIG_DRM_EVDI) += evdi/' >> drivers/gpu/drm/Makefile

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Add Lindroid DRM Loopback (EVDI-based) driver"

    - name: Push new branch
      run: |
        git push origin lindroid-drm-loopback
