name: Direct Patch DRM Loopback to drm-test

on:
  workflow_dispatch:

jobs:
  patch-drm-loopback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Repo (drm-test)
        uses: actions/checkout@v3
        with:
          ref: drm-test
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Clone drm-loopback
        run: |
          git clone --depth=1 https://github.com/yaahallo/drm-loopback loopback-src
          mkdir -p drivers/gpu/drm/drm-loopback
          cp loopback-src/*.c drivers/gpu/drm/drm-loopback/
          cp loopback-src/Makefile drivers/gpu/drm/drm-loopback/
          cp loopback-src/Kconfig  drivers/gpu/drm/drm-loopback/

      - name: Tambah ke Kconfig dan Makefile
        run: |
          grep -q 'drm-loopback/Kconfig' drivers/gpu/drm/Kconfig || \
            echo 'source "drivers/gpu/drm/drm-loopback/Kconfig"' >> drivers/gpu/drm/Kconfig

          grep -q 'drm-loopback/' drivers/gpu/drm/Makefile || \
            echo 'obj-\$(CONFIG_DRM_LOOPBACK) += drm-loopback/' >> drivers/gpu/drm/Makefile

      - name: Commit dan Push
        run: |
          git add drivers/gpu/drm/drm-loopback
          git add drivers/gpu/drm/Kconfig drivers/gpu/drm/Makefile
          git commit -m "Add DRM Loopback driver"
          git push
